# Generated by Django 3.1 on 2020-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=512)),
                ('destination', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
