# Generated by Django 3.1 on 2020-08-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20200824_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='short_url',
            new_name='key',
        ),
    ]
