# Generated by Django 3.1 on 2020-08-24 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20200824_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(choices=[('mobile', 'mobile'), ('tablet', 'tablet'), ('desktop', 'desktop')], max_length=16)),
                ('browser', models.CharField(max_length=128)),
                ('session_key', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
