# Generated by Django 3.1 on 2020-08-24 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0006_auto_20200824_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='hits',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='short_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shortener.shortenedurl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='platform',
            field=models.CharField(choices=[('mobile', 'mobile'), ('tablet', 'tablet'), ('desktop', 'desktop')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='visit',
            name='session_key',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
