# Generated by Django 3.1 on 2020-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20200824_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='suggested_path',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
