# Generated by Django 3.1 on 2020-08-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20200824_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='key',
            field=models.CharField(db_index=True, default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_visits', models.JSONField(default={})),
                ('unique_visits', models.JSONField(default={})),
                ('short_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytic', to='shortener.shortenedurl')),
            ],
        ),
    ]
