# Generated by Django 3.1 on 2020-08-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20200824_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='all_visits',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='unique_visits',
            field=models.JSONField(default=dict),
        ),
    ]
